'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowRight, Download, Send, WalletCards } from 'lucide-react'
import { formatINR } from '@/lib/mock-data'
import { useBank } from '@/components/phase3-pages'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

export function AccountsPage() {
  const { accounts } = useBank()
  return <div className="mx-auto max-w-[1120px]">
    <div className="mb-7"><h1 className="text-2xl font-semibold tracking-tight text-[#203b50]">Accounts</h1><p className="mt-1 text-sm text-[#78909d]">View and manage your Tensorik FinBank accounts.</p></div>
    <div className="grid gap-5 lg:grid-cols-3">{accounts.map(account => <Card key={account.id} className="overflow-hidden border-[#e2e9eb] shadow-none"><div className={`h-2 bg-gradient-to-r ${account.accent}`} /><CardHeader className="pb-3"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-[#78909d]">{account.type}</p><CardTitle className="mt-1 text-base text-[#24445b]">{account.name}</CardTitle><p className="mt-2 text-xs tracking-[0.16em] text-[#8ba0aa]">•••• {account.number}</p></div><WalletCards className="size-5 text-[#7795a5]" /></div></CardHeader><CardContent><p className="text-2xl font-semibold tracking-tight text-[#203b50]">{formatINR(account.balance)}.00</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#edf1f2] pt-4"><div><p className="text-[10px] uppercase tracking-wide text-[#9aacb4]">Available</p><p className="mt-1 text-sm font-medium text-[#456579]">{formatINR(account.availableBalance)}</p></div><div><p className="text-[10px] uppercase tracking-wide text-[#9aacb4]">Interest</p><p className="mt-1 text-sm font-medium text-[#456579]">{account.interestRate}</p></div></div><Button variant="outline" className="mt-5 w-full border-[#dce7eb] text-xs text-[#456579]"><Link href={`/accounts/${account.id}`}>View account <ArrowRight data-icon="inline-end" /></Link></Button></CardContent></Card>)}</div>
    <Card className="mt-6 border-[#e2e9eb] shadow-none"><CardHeader><CardTitle className="text-sm text-[#24445b]">Account summary</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3">{accounts.map(account => <div key={account.id} className="rounded-lg bg-[#f6f9fa] p-4"><p className="text-xs text-[#78909d]">{account.name}</p><p className="mt-2 text-lg font-semibold text-[#203b50]">{formatINR(account.balance)}.00</p><p className="mt-1 text-xs text-[#91a3ab]">Opened {account.opened}</p></div>)}</CardContent></Card>
  </div>
}

export function AccountDetailPage({ accountId }: { accountId: string }) {
  const { accounts, transactions } = useBank()
  const account = accounts.find(item => item.id === accountId) || accounts[0]
  const recent = transactions.filter(item => item.accountId === account.id).slice(0, 5)
  return <div className="mx-auto max-w-[1120px]"><Link href="/accounts" className="mb-5 inline-flex items-center gap-2 text-xs font-medium text-[#4a7893] hover:underline"><ArrowLeft data-icon="inline-start" /> All accounts</Link><div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><Card className={`overflow-hidden border-0 bg-gradient-to-br ${account.accent} text-white shadow-sm`}><CardContent className="p-7"><div className="flex items-start justify-between"><div><p className="text-xs text-white/70">{account.name}</p><p className="mt-2 text-sm tracking-[0.18em] text-white/65">•••• {account.number}</p></div><WalletCards className="size-6 text-white/60" /></div><p className="mt-12 text-3xl font-semibold tracking-tight">{formatINR(account.balance)}.00</p><div className="mt-6 grid grid-cols-2 gap-4 border-t border-white/15 pt-4"><div><p className="text-[10px] text-white/60">Available balance</p><p className="mt-1 text-sm font-medium">{formatINR(account.availableBalance)}</p></div><div><p className="text-[10px] text-white/60">Status</p><p className="mt-1 text-sm font-medium">{account.status}</p></div></div></CardContent></Card><Card className="border-[#e2e9eb] shadow-none"><CardHeader><CardTitle className="text-sm text-[#24445b]">Account actions</CardTitle></CardHeader><CardContent className="grid gap-2"><Button className="justify-start bg-[#173a66] text-xs hover:bg-[#214d80]"><Link href="/transfers"><Send data-icon="inline-start" /> Transfer money</Link></Button><Button variant="outline" className="justify-start border-[#dce7eb] text-xs text-[#456579]"><Link href={`/transactions?account=${account.id}`}>View transactions</Link></Button><Button variant="outline" className="justify-start border-[#dce7eb] text-xs text-[#456579]" onClick={() => window.alert('Statement download prepared for demo.')}><Download data-icon="inline-start" /> Download statement</Button></CardContent></Card></div><Card className="mt-5 border-[#e2e9eb] shadow-none"><CardHeader><CardTitle className="text-sm text-[#24445b]">Recent activity</CardTitle></CardHeader><CardContent className="grid gap-2">{recent.map(transaction => <div key={transaction.id} className="flex items-center justify-between border-b border-[#edf1f2] py-3 last:border-0"><div><p className="text-sm font-medium text-[#36566b]">{transaction.description}</p><p className="mt-1 text-xs text-[#91a3ab]">{transaction.date} · {transaction.status}</p></div><p className={`text-sm font-semibold ${transaction.type === 'credit' ? 'text-[#34805f]' : 'text-[#456579]'}`}>{transaction.type === 'credit' ? '+' : '-'}{formatINR(transaction.amount)}</p></div>)}</CardContent></Card></div>
}
