export type Account = { id: string; type: 'Savings' | 'Current' | 'Fixed Deposit'; name: string; number: string; balance: number; availableBalance: number; currency: 'INR'; status: 'Active'; accent: string; interestRate: string; opened: string; tenure?: string; maturityDate?: string }
export type Transaction = { id: string; date: string; sortDate: string; time: string; description: string; merchant: string; category: string; accountId: string; amount: number; type: 'credit' | 'debit'; status: 'Completed' | 'Pending' | 'Failed'; reference: string; details: string }
export const categories = ['Income', 'Shopping', 'Food', 'Bills', 'Travel', 'Entertainment', 'Healthcare', 'Transfer', 'Utilities', 'Other']
export const transactionStatuses = ['Completed', 'Pending', 'Failed'] as const
export const accounts: Account[] = [
 { id: 'savings', type: 'Savings', name: 'Savings Account', number: '4821', balance: 842350, availableBalance: 838420, currency: 'INR', status: 'Active', accent: 'from-[#193b68] to-[#2e6da4]', interestRate: '4.00%', opened: '12 Jan 2024' },
 { id: 'current', type: 'Current', name: 'Current Account', number: '1094', balance: 624100, availableBalance: 611800, currency: 'INR', status: 'Active', accent: 'from-[#31536c] to-[#5c8496]', interestRate: '2.50%', opened: '06 Mar 2023' },
 { id: 'fd', type: 'Fixed Deposit', name: 'Fixed Deposit Account', number: '7732', balance: 1020000, availableBalance: 1020000, currency: 'INR', status: 'Active', accent: 'from-[#324558] to-[#758897]', interestRate: '7.10%', opened: '18 Aug 2025', tenure: '24 months', maturityDate: '18 Aug 2027' },
]
const row = (id: string, date: string, sortDate: string, time: string, description: string, merchant: string, category: string, accountId: string, amount: number, type: 'credit' | 'debit', status: Transaction['status'], reference: string, details: string): Transaction => ({ id, date, sortDate, time, description, merchant, category, accountId, amount, type, status, reference, details })
export const transactions: Transaction[] = [
 row('t1','18 Sep 2026','2026-09-18','6:18 PM','Amazon India','Amazon India','Shopping','savings',4299,'debit','Completed','TXN-20260918-4821','Online purchase'), row('t2','18 Sep 2026','2026-09-18','9:00 AM','Salary Credit','Tensorik Technologies','Income','savings',85000,'credit','Completed','TXN-20260918-8500','Monthly salary credit'), row('t3','17 Sep 2026','2026-09-17','8:42 PM','Swiggy','Swiggy','Food','current',840,'debit','Completed','TXN-20260917-1094','Food delivery'), row('t4','16 Sep 2026','2026-09-16','11:20 AM','Electricity Bill','BESCOM Utilities','Utilities','current',2340,'debit','Completed','TXN-20260916-1094','Monthly utility payment'), row('t5','14 Sep 2026','2026-09-14','5:32 PM','Uber India','Uber India','Travel','savings',620,'debit','Pending','TXN-20260914-4821','Ride payment'), row('t6','12 Sep 2026','2026-09-12','2:15 PM','Apollo Pharmacy','Apollo Pharmacy','Healthcare','current',1850,'debit','Completed','TXN-20260912-1094','Healthcare purchase'), row('t7','10 Sep 2026','2026-09-10','10:10 AM','Rent Transfer','A. Kumar','Transfer','current',28000,'debit','Completed','TXN-20260910-1094','Monthly rent transfer'), row('t8','08 Sep 2026','2026-09-08','4:45 PM','Refund - Myntra','Myntra','Shopping','savings',2199,'credit','Completed','TXN-20260908-4821','Refund for returned order'), row('t9','05 Sep 2026','2026-09-05','7:00 PM','Netflix','Netflix','Entertainment','current',649,'debit','Failed','TXN-20260905-1094','Subscription payment'), row('t10','01 Sep 2026','2026-09-01','9:30 AM','Interest Credit','Tensorik FinBank','Income','savings',3120,'credit','Completed','TXN-20260901-4821','Savings interest credit'), row('t11','28 Aug 2026','2026-08-28','1:35 PM','BookMyShow','BookMyShow','Entertainment','savings',1240,'debit','Completed','TXN-20260828-4821','Movie tickets'), row('t12','25 Aug 2026','2026-08-25','12:10 PM','Flight Booking','IndiGo','Travel','current',12400,'debit','Completed','TXN-20260825-1094','Domestic flight booking'),
]
export type Card = { id: string; name: string; type: 'Debit' | 'Credit' | 'Virtual'; number: string; expiry: string; status: 'Active' | 'Frozen' | 'Expired'; limit: number; available: number; accent: string; online: boolean; international: boolean; contactless: boolean }
export type Beneficiary = { id: string; name: string; bank: string; account: string; ifsc: string; nickname: string; status: 'Active'; lastUsed: string }
export type Transfer = { id: string; beneficiaryId: string; beneficiaryName: string; accountId: string; amount: number; purpose: string; status: 'Completed' | 'Pending' | 'Failed'; date: string; reference: string }
export type ScheduledPayment = { id: string; name: string; recipient: string; accountId: string; amount: number; frequency: 'Weekly' | 'Monthly' | 'Quarterly' | 'Yearly'; nextPayment: string; status: 'Active' | 'Paused' }
export const cards: Card[] = [
 { id:'debit', name:'Tensorik FinBank Debit Card', type:'Debit', number:'4821', expiry:'09/29', status:'Active', limit:50000, available:50000, accent:'from-[#173a66] to-[#32698f]', online:true, international:false, contactless:true },
 { id:'credit', name:'Tensorik FinBank Credit Card', type:'Credit', number:'7614', expiry:'04/28', status:'Active', limit:200000, available:164500, accent:'from-[#294a61] to-[#6b8b99]', online:true, international:true, contactless:true },
 { id:'virtual', name:'Virtual Card', type:'Virtual', number:'9037', expiry:'11/27', status:'Active', limit:100000, available:100000, accent:'from-[#3d6376] to-[#91aeb8]', online:true, international:false, contactless:false },
]
export const beneficiaries: Beneficiary[] = [
 { id:'rahul', name:'Rahul Sharma', bank:'HDFC Bank', account:'9132', ifsc:'HDFC0001234', nickname:'Personal', status:'Active', lastUsed:'12 Sep 2026' },
 { id:'priya', name:'Priya Singh', bank:'ICICI Bank', account:'2381', ifsc:'ICIC0004567', nickname:'Family', status:'Active', lastUsed:'04 Sep 2026' },
 { id:'aarav', name:'Aarav Mehta', bank:'Axis Bank', account:'7745', ifsc:'UTIB0008912', nickname:'', status:'Active', lastUsed:'28 Aug 2026' },
]
export const transfers: Transfer[] = [{ id:'tr1', beneficiaryId:'rahul', beneficiaryName:'Rahul Sharma', accountId:'current', amount:28000, purpose:'Monthly rent', status:'Completed', date:'10 Sep 2026', reference:'TXN-20260910-1094' }]
export const scheduledPayments: ScheduledPayment[] = [
 { id:'sp1', name:'Netflix', recipient:'Netflix', accountId:'current', amount:649, frequency:'Monthly', nextPayment:'25 Sep 2026', status:'Active' },
 { id:'sp2', name:'Electricity Bill', recipient:'BESCOM Utilities', accountId:'current', amount:2340, frequency:'Monthly', nextPayment:'28 Sep 2026', status:'Active' },
 { id:'sp3', name:'Rent', recipient:'A. Kumar', accountId:'current', amount:18000, frequency:'Monthly', nextPayment:'01 Oct 2026', status:'Active' },
 { id:'sp4', name:'Insurance', recipient:'HDFC Life', accountId:'savings', amount:7500, frequency:'Monthly', nextPayment:'05 Oct 2026', status:'Paused' },
]
export const navItems = [{ label: 'Dashboard', href: '/', group: 'MAIN', icon: 'LayoutDashboard' }, { label: 'Accounts', href: '/accounts', group: 'MAIN', icon: 'WalletCards' }, { label: 'Transactions', href: '/transactions', group: 'MAIN', icon: 'ArrowLeftRight' }, { label: 'Cards', href: '/cards', group: 'MAIN', icon: 'CreditCard' }, { label: 'Transfers', href: '/transfers', group: 'PAYMENTS', icon: 'Send' }, { label: 'Beneficiaries', href: '/beneficiaries', group: 'PAYMENTS', icon: 'Users' }, { label: 'Scheduled Payments', href: '/scheduled-payments', group: 'PAYMENTS', icon: 'CalendarClock' }, { label: 'Analytics', href: '/analytics', group: 'INSIGHTS', icon: 'ChartNoAxesCombined' }, { label: 'Statements', href: '/statements', group: 'INSIGHTS', icon: 'FileText' }, { label: 'Settings', href: '/settings', group: 'OTHER', icon: 'Settings' }, { label: 'Help Center', href: '/help', group: 'OTHER', icon: 'CircleHelp' }]
export const formatINR = (amount: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount)
export const notifications = [{ title: 'Salary credit received', body: '₹85,000 was added to your Savings Account.', time: '2 hours ago' }, { title: 'Statement ready', body: 'Your September statement is available to view.', time: 'Yesterday' }, { title: 'Card payment confirmed', body: 'Your Amazon India payment was successful.', time: 'Yesterday' }]
export const pageDescriptions: Record<string, string> = { Accounts: 'View and manage your Tensorik FinBank accounts.', Transactions: 'Review your recent account activity.', Cards: 'Manage your physical and virtual cards.', Transfers: 'Move money securely between accounts.', Beneficiaries: 'Manage your saved payment recipients.', 'Scheduled Payments': 'Keep track of your upcoming payments.', Analytics: 'Understand your financial patterns at a glance.', Statements: 'Access your monthly account statements.', Profile: 'Manage your personal information.', Preferences: 'Customize your FinBank experience.', Security: 'Manage your account security and activity.', Settings: 'Manage your application settings.', 'Help Center': 'Find answers and get support.' }
